version: "3.8"

services:
  mongodb:
    restart: on-failure
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongo --eval \"db.adminCommand('ping')\"" ]
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  mongodb_data:
