### Create Tasks
POST {{base_url}}/tasks
Content-Type: application/json

{
  "title": "My first task",
  "description": "Hello world!",
  "completed": false
}

### Get All Tasks
GET {{base_url}}/tasks

### Update Task
< {%
    request.variables.set("task_id", "")
%}
PUT {{base_url}}/tasks/{{task_id}}
Content-Type: application/json

{
  "completed": true
}

### Get Task by ID
< {%
    request.variables.set("task_id", "")
%}
GET {{base_url}}/tasks/{{task_id}}

### Get Task by ID
< {%
    request.variables.set("task_id", "")
%}
GET {{base_url}}/tasks/{{task_id}}

### Delete Task
< {%
    request.variables.set("task_id", "")
%}
DELETE {{base_url}}/tasks/{{task_id}}

### Get Task by ID
< {%
    request.variables.set("task_id", "")
%}
GET {{base_url}}/tasks/{{task_id}}
