version: "3.8"

services:
  app:
    restart: on-failure
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    restart: on-failure
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongo --eval \"db.adminCommand('ping')\"" ]
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  mongodb_data:
